---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  become: true
  roles:
    - common

- name: configure and deploy the kafka cluster
  hosts: kafkas
  remote_user: root
  become: true
  roles:
    - kafka
